'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sandbox.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liebe Versuchsperson,
        '''
        '''vielen Dank für Ihre Teilnahme an dieser Studie!
        '''
        '''Die Studie wird aus mehreren Aufgaben bestehen, die Sie nacheinander bearbeiten.
        '''
        '''
        '''Starten Sie mit dem ersten Teil der Studie, indem Sie den &quot;Weiter&quot;-Button drücken..
        '''</summary>
        Friend ReadOnly Property _0_mainInstr() As String
            Get
                Return ResourceManager.GetString("_0_mainInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEST THIS IS A TEST
        '''
        '''TEST.
        '''</summary>
        Friend ReadOnly Property _1_otherInstr() As String
            Get
                Return ResourceManager.GetString("_1_otherInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In der folgenden Phase möchten wir untersuchen, wie schnell Menschen die Valenz von Wörtern feststellen können. Damit ist gemeint, wie schnell Menschen darin sind, ein präsentiertes Wort entweder als &quot;positiv&quot; oder als &quot;negativ&quot; zu klassifizieren.
        '''
        '''Im Zuge jeder einzelnen Klassifizierung werden Sie zwei Wörter sehen. Das erste Wort wird nur sehr kurz auf dem Bildschirm zu sehen sein, unter Umständen sogar so kurz, dass Sie nicht in der Lage sind, es zu identifizieren. Das zweite Wort wird so lange zu sehe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_practiceAneg() As String
            Get
                Return ResourceManager.GetString("_2_practiceAneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In der folgenden Phase möchten wir untersuchen, wie schnell Menschen die Valenz von Wörtern feststellen können. Damit ist gemeint, wie schnell Menschen darin sind, ein präsentiertes Wort entweder als &quot;positiv&quot; oder als &quot;negativ&quot; zu klassifizieren.
        '''
        '''Im Zuge jeder einzelnen Klassifizierung werden Sie zwei Wörter sehen. Das erste Wort wird nur sehr kurz auf dem Bildschirm zu sehen sein, unter Umständen sogar so kurz, dass Sie nicht in der Lage sind, es zu identifizieren. Das zweite Wort wird so lange zu sehe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_practiceApos() As String
            Get
                Return ResourceManager.GetString("_2_practiceApos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben die Übungsphase nun beendet.
        '''
        '''Als nächstes folgt die Testphase, welche identisch zur Übungsphase ist, aber etwas länger dauert.
        '''
        '''Die Zuteilung der Tasten zu &quot;positiv&quot; und &quot;negativ&quot; bleibt ebenfalls genauso wie in der Übungsphase:
        '''
        '''Drücken Sie bitte die Taste &quot;A&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;negativ&quot; ist.
        '''Drücken Sie bitte die Taste &quot;L&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;positiv&quot; ist.
        '''
        '''Denken Sie daran, die präsentierten Wörter so schnell und akkurat wie mög [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3_experimentAneg() As String
            Get
                Return ResourceManager.GetString("_3_experimentAneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben die Übungsphase nun beendet.
        '''
        '''Als nächstes folgt die Testphase, welche identisch zur Übungsphase ist, aber etwas länger dauert.
        '''
        '''Die Zuteilung der Tasten zu &quot;positiv&quot; und &quot;negativ&quot; bleibt ebenfalls genauso wie in der Übungsphase:
        '''
        '''Drücken Sie bitte die Taste &quot;A&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;positiv&quot; ist.
        '''Drücken Sie bitte die Taste &quot;L&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;negativ&quot; ist.
        '''
        '''Denken Sie daran, die präsentierten Wörter so schnell und akkurat wie mög [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3_experimentApos() As String
            Get
                Return ResourceManager.GetString("_3_experimentApos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben die Klassifizierungsphase nun beendet.
        '''
        '''Als nächstes möchten wir Ihnen noch einige Fragen zu den Wörtern stellen, die Sie während der letzten Phase gesehen haben.
        '''
        '''
        '''Drücken Sie den &quot;Weiter&quot;-Button um fortzufahren..
        '''</summary>
        Friend ReadOnly Property _4_explicitInstr() As String
            Get
                Return ResourceManager.GetString("_4_explicitInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _5_demoInstr() As String
            Get
                Return ResourceManager.GetString("_5_demoInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''Das Experiment ist nun beendet.
        '''
        '''Nochmals vielen Dank für Ihre Teilnahme!
        '''
        '''Wenden Sie sich bitte an die Versuchsleitung..
        '''</summary>
        Friend ReadOnly Property _6_endInstr() As String
            Get
                Return ResourceManager.GetString("_6_endInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BlockRandomisation() As String
            Get
                Return ResourceManager.GetString("BlockRandomisation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property experimentPrime_Neg() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property experimentPrime_Pos() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property experimentPrime_Str() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property experimentTarget_Neg() As String
            Get
                Return ResourceManager.GetString("experimentTarget_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property experimentTarget_Pos() As String
            Get
                Return ResourceManager.GetString("experimentTarget_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property practicePrime_Neg() As String
            Get
                Return ResourceManager.GetString("practicePrime_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property practicePrime_Pos() As String
            Get
                Return ResourceManager.GetString("practicePrime_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property practicePrime_Str() As String
            Get
                Return ResourceManager.GetString("practicePrime_Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property practiceTarget_Neg() As String
            Get
                Return ResourceManager.GetString("practiceTarget_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property practiceTarget_Pos() As String
            Get
                Return ResourceManager.GetString("practiceTarget_Pos", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
